//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;symbol&quot;:&quot;WINS&quot;,&quot;companyName&quot;:&quot;Wins Finance Holdings Inc.&quot;,&quot;primaryExchange&quot;:&quot;NASDAQ Capital Market&quot;,&quot;sector&quot;:&quot;Financial Services&quot;,&quot;calculationPrice&quot;:&quot;sip&quot;,&quot;open&quot;:15.55,&quot;openTime&quot;:1560433390110,&quot;close&quot;:15.3,&quot;closeTime&quot;:1560369600550,&quot;high&quot;:15.55,&quot;low&quot;:15.55,&quot;latestPrice&quot;:15.55,&quot;latestSource&quot;:&quot;15 minute delayed price&quot;,&quot;latestTime&quot;:&quot;9:43:10 AM&quot;,&quot;latestUpdate&quot;:1560433390110,&quot;latestVolume&quot;:162,&quot;iexRealtimePrice&quot;:0,&quot;iexRealtimeSize&quot;:0,&quot;iexLastUpdated&quot;:0,&quot;delayedPrice&quot;:15.55,&quot;delayedPriceTime&quot;:1560433390110,&quot;ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gainers {
            get {
                return ResourceManager.GetString("gainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;symbol&quot;:&quot;SVRA&quot;,&quot;companyName&quot;:&quot;Savara Inc.&quot;,&quot;primaryExchange&quot;:&quot;Nasdaq Global Select&quot;,&quot;sector&quot;:&quot;Healthcare&quot;,&quot;calculationPrice&quot;:&quot;tops&quot;,&quot;open&quot;:2.67,&quot;openTime&quot;:1560432600937,&quot;close&quot;:10.57,&quot;closeTime&quot;:1560369600344,&quot;high&quot;:2.89,&quot;low&quot;:2.55,&quot;latestPrice&quot;:2.635,&quot;latestSource&quot;:&quot;IEX real time price&quot;,&quot;latestTime&quot;:&quot;12:36:42 PM&quot;,&quot;latestUpdate&quot;:1560443802500,&quot;latestVolume&quot;:6788851,&quot;iexRealtimePrice&quot;:2.635,&quot;iexRealtimeSize&quot;:100,&quot;iexLastUpdated&quot;:1560443802500,&quot;delayedPrice&quot;:2.645,&quot;delayedPriceTime&quot;:1560442925636,&quot;extended [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string losers {
            get {
                return ResourceManager.GetString("losers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;symbol&quot;:&quot;AMD&quot;,&quot;companyName&quot;:&quot;Advanced Micro Devices Inc.&quot;,&quot;primaryExchange&quot;:&quot;Nasdaq Global Select&quot;,&quot;sector&quot;:&quot;Technology&quot;,&quot;calculationPrice&quot;:&quot;tops&quot;,&quot;open&quot;:32.35,&quot;openTime&quot;:1560432600684,&quot;close&quot;:32.18,&quot;closeTime&quot;:1560369600311,&quot;high&quot;:32.5,&quot;low&quot;:31.35,&quot;latestPrice&quot;:31.415,&quot;latestSource&quot;:&quot;IEX real time price&quot;,&quot;latestTime&quot;:&quot;12:35:56 PM&quot;,&quot;latestUpdate&quot;:1560443756604,&quot;latestVolume&quot;:36423889,&quot;iexRealtimePrice&quot;:31.415,&quot;iexRealtimeSize&quot;:206,&quot;iexLastUpdated&quot;:1560443756604,&quot;delayedPrice&quot;:31.48,&quot;delayedPriceTime&quot;:156 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mostactive {
            get {
                return ResourceManager.GetString("mostactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;symbol&quot;:&quot;A&quot;,&quot;name&quot;:&quot;Agilent Technologies Inc.&quot;,&quot;date&quot;:&quot;2019-06-13&quot;,&quot;isEnabled&quot;:true,&quot;type&quot;:&quot;cs&quot;,&quot;iexId&quot;:&quot;2&quot;},{&quot;symbol&quot;:&quot;AA&quot;,&quot;name&quot;:&quot;Alcoa Corporation&quot;,&quot;date&quot;:&quot;2019-06-13&quot;,&quot;isEnabled&quot;:true,&quot;type&quot;:&quot;cs&quot;,&quot;iexId&quot;:&quot;12042&quot;},{&quot;symbol&quot;:&quot;AAAU&quot;,&quot;name&quot;:&quot;Perth Mint Physical Gold&quot;,&quot;date&quot;:&quot;2019-06-13&quot;,&quot;isEnabled&quot;:true,&quot;type&quot;:&quot;N/A&quot;,&quot;iexId&quot;:&quot;14924&quot;},{&quot;symbol&quot;:&quot;AABA&quot;,&quot;name&quot;:&quot;Altaba Inc.&quot;,&quot;date&quot;:&quot;2019-06-13&quot;,&quot;isEnabled&quot;:true,&quot;type&quot;:&quot;cs&quot;,&quot;iexId&quot;:&quot;7653&quot;},{&quot;symbol&quot;:&quot;AAC&quot;,&quot;name&quot;:&quot;AAC Holdings Inc.&quot;,&quot;date&quot;:&quot;2019-06-13&quot;,&quot;isEnabl [re....
        /// </summary>
        internal static string stocks {
            get {
                return ResourceManager.GetString("stocks", resourceCulture);
            }
        }
    }
}
